apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-nw-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: api-pod # from which pod traffic is allowed
        namespaceSelector:
          matchLabels:
            name: prod
      - ipBlock:
          cidr: 192.168.0.5/32

      ports:
        - protocol: TCP
          port: 3306