apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    tier: backend
spec:
  containers:
  - name: nginxpod
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: color
        value: blue
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            key: APP_COLOR
            name: config-map
    envFrom:
      - configMapRef:
          name: config-map
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: color
              operator: In
              values:
                - "blue"
  schedulerName: kube-scheduler
  nodeName: node02 # can only be done at creation time